FROM node:14-alpine

RUN mkdir -p /home/app/node && chown node /home/app/node

RUN npm install prisma1 --unsafe-pern

WORKDIR /home/app/node 

USER node

COPY package.json ${WORKDIR}

RUN yarn install

COPY . ${WORKDIR}

ENV HOST=0.0.0.0 PORT=3000

EXPOSE ${PORT}

#CMD ["yarn", "start"]

CMD ["yarn", "start", "deploy"]
